# Simple workflow for deploying static content to GitHub Pages
name: Issue Release

on:
  # Run when Docs workflow completes
  push:
    branches:
      - release/*

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  issue-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'api-clients'

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ github.ref_name }}"
          body: "Release ${{ github.ref_name }}."
          files: |
            galv-spec.json
            clients/*
          target_commitish: "${{ github.ref_name }}"
