# Simple workflow for deploying static content to GitHub Pages
name: Issue Release

on:
  # Run when Docs workflow completes
  push:
    branches:
      - releases/**

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  issue-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'api-clients'

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: github.ref_name
          body: "Release ${{ github.ref_name }}."
          artifacts: "galv-spec.json,clients/*"
          commit: github.ref_name
          artifactErrorsFailBuild: true
